### ISSUE TITLE
Cant not build with webpack@latest (@4.10.0)

### ISSUE THREAD

**Issue by alexlevn** [jackreichert/a-wp-react-redux-theme#14]
I tried to build with webpack but get this error message:

module.js:540
    throw err;
    ^
Error: Cannot find module 'webpack/schemas/WebpackOptions.json'
    at Function.Module._resolveFilename (module.js:538:15)

Then: I checked my webpack version in global package
webpack-v:
+ webpack@4.10.0

I changed to webpack@3 with these comands:
        npm uninstall -g webpack webpack-cli
        npm i -g webpack@3 webpack-cli@2

Now I builded: success.
It got error with webpack latest version (@4.10.0), can you fixed this with webpack@latest version.
It took me 4 hours to know how to fixed this.

**Comment by jackreichert** [comment]
Oh dear, thanks for this. I'll look into the issue.
